// This file has been generated by Specta. DO NOT EDIT.

export type Joint = {
  name: string
  id: string
  mesh_id: string
  constraints: Constraint | null
}

export type TauRpcRootApiOutputTypes = {
  proc_name: 'get_configs'
  output_type: Config[]
}

export type Constraint = {
  axis: string
  min: number
  home: number
  max: number
}

export type TauRpcRootApiInputTypes = {
  proc_name: 'get_configs'
  input_type: null
}

export type TauRpcEventsOutputTypes = {
  proc_name: 'configs_changed'
  output_type: null
}

export type Config = {
  name: string
  description: string
  model_path: string
  joints: Joint[]
  tcp_offset: number[]
}

export type TauRpcEventsInputTypes = {
  proc_name: 'configs_changed'
  input_type: { __taurpc_type: Config[] }
}

const ARGS_MAP = {
  '': '{"get_configs":[]}',
  'events': '{"configs_changed":["configs"]}',
}
import { createTauRPCProxy as createProxy } from 'taurpc'

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
  '': [TauRpcRootApiInputTypes, TauRpcRootApiOutputTypes]
  'events': [TauRpcEventsInputTypes, TauRpcEventsOutputTypes]
}
