// This file has been generated by Specta. DO NOT EDIT.

export type TauRpcOutputs = { proc_name: "_hello_world_"; output_type: null } | { proc_name: "event_test"; output_type: null }

export type TauRpcInputs = { proc_name: "_hello_world_"; input_type: null } | { proc_name: "event_test"; input_type: null }


import { createTauRPCProxy as createProxy } from "taurpc"

type Router = {
	root: [TauRpcInputs, TauRpcOutputs]
}

export const createTauRPCProxy = () => createProxy<Router>()
